### ISSUE TITLE
feat request: support to configure recap and autorecap to control where to send recaps

### ISSUE THREAD

**Issue by nekomeowww** [nekomeowww/insights-bot#117]
### Scenario 1

In group 1:

Creator: `/enable_recap`
Bot: ask for recap mode, whether publicly or privately
Creator: Select
          -> if privately is selected, check if user is creator or not, if not a creator, reject the request
Bot: deletes `/enable_recap` from creator, deletes selections from Bot

### Scenario 2

In group 1:

Creator: `/configure_recap`
Bot: ask for recap mode, whether publicly or privately
Creator: Select
          -> if privately is selected, check if user is creator or not, if not a creator, reject the request
Bot: deletes `/configure_recap` from creator, deletes selections from Bot

### Scenario 3

In group 1:

User: `/recap`
Bot: -> Try to send a message to state out the process is started.
          -> if it fails to do so, send `/start` and reply to user (ask user to enable the bot or unblock the bot)
          -> if it succeeded, proceed to summarize the chat histories from targeted group and send to user
Bot: deletes `/recap` from user，deletes `/start` from Bot

### Scenario 4

In group 1:

User: `/subscribe_recap`
Bot: -> Try to send a message to state out whether the action has succeeded.
          -> if it fails to do so, send `/start` and reply to user (ask user to enable the bot or unblock the bot)
          -> if it succeeded, proceed to subscribe auto recaps for user
`<after time interval to send auto recaps>`
Bot: look for subscribed users and try to summarize the chat histories from targeted group and send to user, if it fails to do so, ignore.

by @KexyBiscuit

**Comment by KexyBiscuit** [comment]
LGTM

Whether Telegram fails the message sending when the user blocks the bot via platform features is unknown, test needed.
