### ISSUE TITLE
improve: grammar issue in the title of readme

### ISSUE THREAD

**Issue by LemonNekoGH** [nekomeowww/insights-bot#78]
https://github.com/nekomeowww/insights-bot/blob/f48968ac37d6ce690f629fd124405b56a924cc7a/README.md?plain=1#L31
It should be `Supported` not `Support`

**Comment by nekomeowww** [comment]
@LemonNekoGH 不至于说是 syntax error 吧，就是个 grammar issue，感觉说的好严重
